rtl_tcp:
  host: "*.*.*.*"
  port: 1234

receiver:
  frequency: 98000000  # 915 MHz
  sample_rate: 2048000  # 2.048 MHz
  fft_size: 2048

detector:
  power_threshold: -70
  bandwidth_threshold: 100000  # 100 kHz
  z_score_threshold: 1.5
  detection_window: 5
  min_duration: 0.1
  test_mode: false

display:
  waterfall_length: 50
  update_interval: 50  # milliseconds