services:
  rtl-sdr:
    image: alpine:latest
    container_name: rtl-tcp
    restart: unless-stopped
    network_mode: "host" 
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  
    volumes:
      - ./rtl_sdr_setup:/setup  
    entrypoint: >
      sh -c "
      apk add --no-cache rtl-sdr bash &&
      echo 'blacklist dvb_usb_rtl28xxu' > /etc/modprobe.d/blacklist-dvb.conf &&
      rtl_tcp -a 0.0.0.0 -b 40
      "
